# Generated by Django 6.1 on 2026-08-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['asset_code'], 'verbose_name': '资产', 'verbose_name_plural': '资产'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '物品分类', 'verbose_name_plural': '物品分类'},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'ordering': ['category__name', 'name'], 'verbose_name': '物品类型', 'verbose_name_plural': '物品类型'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['warehouse__name', 'code'], 'verbose_name': '库位', 'verbose_name_plural': '库位'},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['name'], 'verbose_name': '耗材', 'verbose_name_plural': '耗材'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': '仓库', 'verbose_name_plural': '仓库'},
        ),
    ]
