# Generated by Django 6.1 on 2026-08-25 05:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_asset_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacturer_barcode',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_order_no',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('in_stock', '在库'), ('borrowed', '已借出'), ('issued', '已领用'), ('pending_out', '待出库'), ('pending_return', '待归还验收'), ('pending_inspection', '待质检'), ('maintenance', '待维修'), ('repairing', '维修中'), ('sold', '已售出'), ('returned_to_vendor', '已退供应商'), ('scrapped', '已报废'), ('damaged', '已报损'), ('lost', '已丢失'), ('disabled', '已停用')], default='in_stock', max_length=32),
        ),
        migrations.CreateModel(
            name='AssetNetworkEndpoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interface_name', models.CharField(blank=True, default='', max_length=80)),
                ('ip_address', models.GenericIPAddressField()),
                ('subnet_mask', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, default='', max_length=32)),
                ('hostname', models.CharField(blank=True, default='', max_length=120)),
                ('vlan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_endpoints', to='inventory.asset')),
            ],
            options={
                'verbose_name': '网络接口信息',
                'verbose_name_plural': '网络接口信息',
                'ordering': ['asset__asset_code', '-is_primary', 'interface_name', 'ip_address'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_filename', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('previewed', '待复核'), ('imported', '已导入'), ('failed', '导入失败')], default='previewed', max_length=20)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('imported_asset_count', models.PositiveIntegerField(default=0)),
                ('imported_network_endpoint_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '历史数据导入批次',
                'verbose_name_plural': '历史数据导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='source_import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inventory.importbatch'),
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sheet_name', models.CharField(max_length=120)),
                ('row_number', models.PositiveIntegerField()),
                ('severity', models.CharField(choices=[('info', '提示'), ('warning', '需复核'), ('error', '无法导入')], default='warning', max_length=12)),
                ('code', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=255)),
                ('source_data', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_note', models.CharField(blank=True, default='', max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='inventory.importbatch')),
            ],
            options={
                'verbose_name': '导入复核问题',
                'verbose_name_plural': '导入复核问题',
                'ordering': ['batch', 'sheet_name', 'row_number', 'severity'],
            },
        ),
    ]
