# Generated by Django 6.1 on 2026-08-25 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_asset_manufacturer_asset_manufacturer_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='imported_stock_item_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='source_import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='inventory.importbatch'),
        ),
    ]
