# Generated by Django 6.1 on 2026-08-25 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_importbatch_imported_stock_item_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['name'], 'verbose_name': '数量库存物料', 'verbose_name_plural': '数量库存物料'},
        ),
        migrations.AddField(
            model_name='asset',
            name='search_aliases',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='asset',
            name='search_index',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='inventory.itemtype'),
        ),
    ]
