# Generated by Django 6.1 on 2026-08-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stockitem_options_asset_search_aliases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='is_serialized',
            field=models.BooleanField(default=True, help_text='启用后每个实物需单独建立资产台账、资产编号和二维码。'),
        ),
    ]
