# Generated by Django 6.1 on 2026-08-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_itemtype_is_serialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='external_holder_company',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='external_holder_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='external_holder_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
