# Generated by Django 6.1 on 2026-08-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_asset_external_holder_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='采购金额（元）'),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_until',
            field=models.DateField(blank=True, null=True, verbose_name='质保到期日'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='供应商'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='单价（元）'),
        ),
    ]
