# Generated by Django 6.1 on 2026-08-27 01:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_asset_purchase_amount_asset_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCheckLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_quantity', models.PositiveIntegerField(default=0)),
                ('counted_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_asset_code', models.CharField(blank=True, default='', max_length=80)),
                ('expected_serial_number', models.CharField(blank=True, default='', max_length=120)),
                ('expected_status', models.CharField(blank=True, default='', max_length=32)),
                ('result', models.CharField(choices=[('pending', '待盘点'), ('matched', '账实相符'), ('shortage', '盘亏'), ('surplus', '盘盈'), ('location_mismatch', '库位不符')], default='pending', max_length=24)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_check_lines', to='inventory.asset')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_inventory_check_lines', to=settings.AUTH_USER_MODEL)),
                ('expected_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expected_inventory_check_lines', to='inventory.location')),
                ('expected_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expected_inventory_check_lines', to='inventory.warehouse')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_check_lines', to='inventory.itemtype')),
                ('observed_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observed_inventory_check_lines', to='inventory.location')),
                ('observed_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observed_inventory_check_lines', to='inventory.warehouse')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_check_lines', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': '盘点明细',
                'verbose_name_plural': '盘点明细',
                'ordering': ['item_type__name', 'expected_asset_code', 'stock_item__name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_no', models.CharField(default='', max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '盘点中'), ('pending_review', '待复核'), ('completed', '已完成'), ('canceled', '已取消')], default='draft', max_length=24)),
                ('note', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_check_tasks', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_check_tasks', to='inventory.location')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_inventory_check_tasks', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_inventory_check_tasks', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_check_tasks', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': '盘点任务',
                'verbose_name_plural': '盘点任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckScan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_value', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('result', models.CharField(choices=[('resolved', '已识别'), ('duplicate', '重复扫描'), ('not_found', '未找到'), ('out_of_scope', '不在盘点范围')], max_length=24)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_check_scans', to='inventory.asset')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='inventory.inventorycheckline')),
                ('observed_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_check_scans', to='inventory.location')),
                ('observed_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_check_scans', to='inventory.warehouse')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_check_scans', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_check_scans', to='inventory.stockitem')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='inventory.inventorychecktask')),
            ],
            options={
                'verbose_name': '盘点扫描记录',
                'verbose_name_plural': '盘点扫描记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorycheckline',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorychecktask'),
        ),
        migrations.CreateModel(
            name='InventoryCheckAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('surplus', '盘盈调整'), ('shortage', '盘亏调整'), ('location', '盘点位置调整')], max_length=24)),
                ('before_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('after_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('before_status', models.CharField(blank=True, default='', max_length=32)),
                ('after_status', models.CharField(blank=True, default='', max_length=32)),
                ('review_note', models.TextField(blank=True, default='')),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('after_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_inventory_check_adjustments', to='inventory.location')),
                ('after_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_inventory_check_adjustments', to='inventory.warehouse')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_check_adjustments', to='inventory.asset')),
                ('before_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='before_inventory_check_adjustments', to='inventory.location')),
                ('before_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='before_inventory_check_adjustments', to='inventory.warehouse')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_check_adjustments', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_check_adjustments', to='inventory.stockitem')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment', to='inventory.inventorycheckline')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.inventorychecktask')),
            ],
            options={
                'verbose_name': '盘点差异调整台账',
                'verbose_name_plural': '盘点差异调整台账',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorycheckline',
            constraint=models.UniqueConstraint(condition=models.Q(('asset__isnull', False)), fields=('task', 'asset'), name='unique_inventory_check_asset_line'),
        ),
        migrations.AddConstraint(
            model_name='inventorycheckline',
            constraint=models.UniqueConstraint(condition=models.Q(('stock_item__isnull', False)), fields=('task', 'stock_item'), name='unique_inventory_check_stock_line'),
        ),
    ]
