# Generated by Django 6.1 on 2026-08-27 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventorycheckline_inventorychecktask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycheckline',
            name='item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_check_lines', to='inventory.itemtype'),
        ),
    ]
