# Generated by Django 6.1 on 2026-08-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventorycheckline_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycheckadjustment',
            name='action',
            field=models.CharField(choices=[('surplus', '盘盈调整'), ('shortage', '盘亏调整'), ('location', '盘点位置调整'), ('status', '盘点状态修正')], max_length=24),
        ),
        migrations.AlterField(
            model_name='inventorycheckline',
            name='result',
            field=models.CharField(choices=[('pending', '待盘点'), ('matched', '账实相符'), ('shortage', '盘亏'), ('surplus', '盘盈'), ('location_mismatch', '库位不符'), ('status_mismatch', '状态不符')], default='pending', max_length=24),
        ),
    ]
