# Generated by Django 6.1 on 2026-08-27 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventorycheckadjustment_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorychecktask',
            name='reopen_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventorychecktask',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorychecktask',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_inventory_check_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
