# Generated by Django 6.1 on 2026-08-27 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_stock_item_holdings(apps, schema_editor):
    WorkflowRequest = apps.get_model('workflow', 'WorkflowRequest')
    StockItemHolding = apps.get_model('inventory', 'StockItemHolding')
    balances = {}
    requests = WorkflowRequest.objects.filter(
        status='done',
        is_quick_process=False,
        applicant_id__isnull=False,
        request_type__in=['borrow', 'return'],
    ).prefetch_related('lines').order_by('created_at')
    for request_obj in requests.iterator(chunk_size=500):
        direction = 1 if request_obj.request_type == 'borrow' else -1
        for line in request_obj.lines.all():
            if not line.stock_item_id:
                continue
            key = (line.stock_item_id, request_obj.applicant_id)
            balances[key] = max(balances.get(key, 0) + direction * line.quantity, 0)
    StockItemHolding.objects.bulk_create([
        StockItemHolding(stock_item_id=stock_item_id, holder_id=holder_id, quantity=quantity)
        for (stock_item_id, holder_id), quantity in balances.items()
        if quantity > 0
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventory_conversion_and_import_mode'),
        ('workflow', '0010_inventorytransaction_workflow_in_busines_b91837_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItemHolding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_item_holdings', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_holdings', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': '个人耗材借用余额',
                'verbose_name_plural': '个人耗材借用余额',
                'ordering': ['holder__username', 'stock_item__name'],
                'constraints': [models.UniqueConstraint(fields=('stock_item', 'holder'), name='unique_stock_item_holder')],
            },
        ),
        migrations.RunPython(backfill_stock_item_holdings, migrations.RunPython.noop),
    ]
