# Generated by Django 6.1 on 2026-08-28 04:33

import apps.inventory.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_stockitemholding'),
        ('workflow', '0012_inventoryreservation_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHandover',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handover_no', models.CharField(default='', max_length=80, unique=True)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('canceled', '已取消')], default='pending', max_length=20)),
                ('from_holder_name', models.CharField(blank=True, default='', max_length=120)),
                ('to_holder_name', models.CharField(max_length=120)),
                ('handover_date', models.DateField()),
                ('condition_description', models.TextField(blank=True, default='')),
                ('accessories', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='inventory.asset')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_asset_handovers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_asset_handovers', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_handovers_to_confirm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '资产交接记录',
                'verbose_name_plural': '资产交接记录',
                'ordering': ['-handover_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetLifecycleEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('maintenance', '维修'), ('handover', '交接'), ('attachment', '附件归档'), ('scrap_request', '报废申请'), ('note', '其他记录')], max_length=24)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_model', models.CharField(blank=True, default='', max_length=120)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_lifecycle_events', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='inventory.asset')),
            ],
            options={
                'verbose_name': '资产生命周期事件',
                'verbose_name_plural': '资产生命周期事件',
                'ordering': ['-event_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_no', models.CharField(default='', max_length=80, unique=True)),
                ('repair_type', models.CharField(choices=[('internal', '内部维修'), ('external', '外部维修'), ('warranty', '供应商质保')], default='internal', max_length=20)),
                ('status', models.CharField(choices=[('open', '待处理'), ('diagnosing', '故障诊断中'), ('sent_out', '已寄出'), ('waiting_parts', '等待配件'), ('repairing', '维修中'), ('completed', '已完成'), ('canceled', '已取消')], default='open', max_length=24)),
                ('fault_description', models.TextField()),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('service_provider', models.CharField(blank=True, default='', max_length=160)),
                ('rma_no', models.CharField(blank=True, default='', max_length=120)),
                ('outbound_tracking_no', models.CharField(blank=True, default='', max_length=120)),
                ('return_tracking_no', models.CharField(blank=True, default='', max_length=120)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_under_warranty', models.BooleanField(default=False)),
                ('previous_asset_status', models.CharField(blank=True, choices=[('in_stock', '在库'), ('borrowed', '已借出'), ('issued', '已领用'), ('pending_out', '待出库'), ('pending_return', '待归还验收'), ('pending_inspection', '待质检'), ('maintenance', '待维修'), ('repairing', '维修中'), ('sold', '已售出'), ('returned_to_vendor', '已退供应商'), ('scrapped', '已报废'), ('damaged', '已报损'), ('lost', '已丢失'), ('disabled', '已停用'), ('converted_to_stock', '已转为耗材配件')], default='', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='inventory.asset')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('source_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='workflow.workflowrequest')),
            ],
            options={
                'verbose_name': '资产维修台账',
                'verbose_name_plural': '资产维修台账',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.inventory.models.asset_attachment_upload_to)),
                ('display_name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('photo', '现场照片'), ('repair_report', '维修报告'), ('invoice', '发票或费用凭证'), ('shipping', '物流凭证'), ('log', '设备日志'), ('other', '其他资料')], default='other', max_length=24)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='inventory.asset')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_asset_attachments', to=settings.AUTH_USER_MODEL)),
                ('handover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='inventory.assethandover')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='inventory.maintenancerecord')),
            ],
            options={
                'verbose_name': '资产归档附件',
                'verbose_name_plural': '资产归档附件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assethandover',
            index=models.Index(fields=['asset', 'status'], name='inventory_a_asset_i_01ad2e_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlifecycleevent',
            index=models.Index(fields=['asset', 'event_at'], name='inventory_a_asset_i_97d8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['asset', 'status'], name='inventory_m_asset_i_828af4_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['status', 'expected_return_date'], name='inventory_m_status_70ccb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('source_request__isnull', False)), fields=('asset', 'source_request'), name='unique_asset_workflow_maintenance'),
        ),
    ]
