# Generated by Django 6.1 on 2026-09-07 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_assethandover_assetlifecycleevent_maintenancerecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=160, verbose_name='名称')),
                ('contact_name', models.CharField(blank=True, default='', max_length=120, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '客户资料',
                'verbose_name_plural': '客户资料',
                'ordering': ['name', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=160, verbose_name='名称')),
                ('contact_name', models.CharField(blank=True, default='', max_length=120, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '维修服务商资料',
                'verbose_name_plural': '维修服务商资料',
                'ordering': ['name', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=160, verbose_name='名称')),
                ('contact_name', models.CharField(blank=True, default='', max_length=120, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='联系电话')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '供应商资料',
                'verbose_name_plural': '供应商资料',
                'ordering': ['name', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='项目编号')),
                ('name', models.CharField(max_length=160, verbose_name='项目名称')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='inventory.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '项目资料',
                'verbose_name_plural': '项目资料',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='service_provider_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='inventory.serviceprovider', verbose_name='维修服务商资料'),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inventory.supplier', verbose_name='供应商资料'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='supplier_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='inventory.supplier', verbose_name='供应商资料'),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='工单编号')),
                ('name', models.CharField(max_length=160, verbose_name='工单名称')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='inventory.customer', verbose_name='客户')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='inventory.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '工单资料',
                'verbose_name_plural': '工单资料',
                'ordering': ['name', 'code'],
            },
        ),
    ]
