# Generated by Django 5.2.17 on 2026-09-24 06:49

from django.db import migrations, models


def empty_asset_code_to_null(apps, schema_editor):
    # 历史数据里未赋码的资产保存的是空字符串；唯一约束下多个空串会冲突，统一转为 NULL。
    Asset = apps.get_model('inventory', 'Asset')
    Asset.objects.filter(asset_code='').update(asset_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_customer_serviceprovider_supplier_project_and_more'),
    ]

    operations = [
        migrations.RunPython(empty_asset_code_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, default=None, max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('in_stock', '在库'), ('borrowed', '已借出'), ('issued', '已领用'), ('pending_out', '待出库'), ('pending_return', '待归还验收'), ('pending_inspection', '待质检'), ('maintenance', '待维修'), ('repairing', '维修中'), ('sold', '已售出'), ('internal_borrow', '内部借用库'), ('shipped_out', '已出库'), ('returned_to_vendor', '已退供应商'), ('scrapped', '已报废'), ('damaged', '已报损'), ('lost', '已丢失'), ('disabled', '已停用'), ('converted_to_stock', '已转为耗材配件')], default='in_stock', max_length=32),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='previous_asset_status',
            field=models.CharField(blank=True, choices=[('in_stock', '在库'), ('borrowed', '已借出'), ('issued', '已领用'), ('pending_out', '待出库'), ('pending_return', '待归还验收'), ('pending_inspection', '待质检'), ('maintenance', '待维修'), ('repairing', '维修中'), ('sold', '已售出'), ('internal_borrow', '内部借用库'), ('shipped_out', '已出库'), ('returned_to_vendor', '已退供应商'), ('scrapped', '已报废'), ('damaged', '已报损'), ('lost', '已丢失'), ('disabled', '已停用'), ('converted_to_stock', '已转为耗材配件')], default='', max_length=32),
        ),
    ]
