# Generated by Django 5.2.17 on 2026-09-24 07:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_asset_asset_code_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('in_stock', '在库'), ('borrowed', '已借出'), ('issued', '已领用'), ('pending_out', '待出库'), ('pending_return', '待归还验收'), ('pending_inspection', '待质检'), ('maintenance', '待维修'), ('repairing', '维修中'), ('sold', '已售出'), ('internal_borrow', '内部借用库'), ('shipped_out', '已出库'), ('assembled', '已组装'), ('returned_to_vendor', '已退供应商'), ('scrapped', '已报废'), ('damaged', '已报损'), ('lost', '已丢失'), ('disabled', '已停用'), ('converted_to_stock', '已转为耗材配件')], default='in_stock', max_length=32),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='previous_asset_status',
            field=models.CharField(blank=True, choices=[('in_stock', '在库'), ('borrowed', '已借出'), ('issued', '已领用'), ('pending_out', '待出库'), ('pending_return', '待归还验收'), ('pending_inspection', '待质检'), ('maintenance', '待维修'), ('repairing', '维修中'), ('sold', '已售出'), ('internal_borrow', '内部借用库'), ('shipped_out', '已出库'), ('assembled', '已组装'), ('returned_to_vendor', '已退供应商'), ('scrapped', '已报废'), ('damaged', '已报损'), ('lost', '已丢失'), ('disabled', '已停用'), ('converted_to_stock', '已转为耗材配件')], default='', max_length=32),
        ),
        migrations.CreateModel(
            name='CompositeUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_code', models.CharField(blank=True, default=None, max_length=80, null=True, unique=True, verbose_name='成品编码')),
                ('name', models.CharField(max_length=120, verbose_name='成品名称')),
                ('model', models.CharField(blank=True, default='', max_length=120, verbose_name='型号')),
                ('qr_value', models.CharField(blank=True, default='', max_length=255, verbose_name='系统二维码内容')),
                ('status', models.CharField(choices=[('assembled', '已组装'), ('borrowed', '已借出'), ('sold', '已售出'), ('disassembled', '已拆散')], default='assembled', max_length=32, verbose_name='状态')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='备注')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composite_units', to='inventory.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '成品设备',
                'verbose_name_plural': '成品设备',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assembled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='组装时间')),
                ('disassembled_at', models.DateTimeField(blank=True, null=True, verbose_name='拆散时间')),
                ('assemble_request_no', models.CharField(blank=True, default='', max_length=80, verbose_name='组装申请单号')),
                ('disassemble_request_no', models.CharField(blank=True, default='', max_length=80, verbose_name='拆散申请单号')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_links', to='inventory.asset')),
                ('composite_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_links', to='inventory.compositeunit')),
            ],
            options={
                'verbose_name': '成品组装履历',
                'verbose_name_plural': '成品组装履历',
                'ordering': ['-assembled_at'],
                'indexes': [models.Index(fields=['composite_unit', 'disassembled_at'], name='inventory_c_composi_7e36c0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('disassembled_at__isnull', True)), fields=('asset',), name='unique_active_component_link_asset')],
            },
        ),
    ]
