# Generated by Django 5.2.17 on 2026-09-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositeunit',
            name='status',
            field=models.CharField(choices=[('draft', '待组装'), ('assembled', '已组装'), ('borrowed', '已借出'), ('sold', '已售出'), ('disassembled', '已拆散')], default='assembled', max_length=32, verbose_name='状态'),
        ),
    ]
