# Generated by Django 6.1 on 2026-08-25 05:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserListPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_key', models.CharField(max_length=80)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '列表展示偏好',
                'verbose_name_plural': '列表展示偏好',
                'unique_together': {('user', 'list_key')},
            },
        ),
    ]
