# Generated by Django 6.1 on 2026-08-27 02:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_split_warehouse_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySequence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=16)),
                ('sequence_date', models.DateField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '单据日序号',
                'verbose_name_plural': '单据日序号',
                'constraints': [models.UniqueConstraint(fields=('prefix', 'sequence_date'), name='unique_daily_sequence_prefix_date')],
            },
        ),
    ]
