# Generated by Django 6.1 on 2026-10-07 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_dailysequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottleState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '登录限流状态',
                'verbose_name_plural': '登录限流状态',
                'ordering': ['-updated_at'],
            },
        ),
    ]
