# Generated by Django 6.1 on 2026-10-07 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_loginthrottlestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiThrottleState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '接口限流状态',
                'verbose_name_plural': '接口限流状态',
                'ordering': ['-updated_at'],
            },
        ),
    ]
