# Generated by Django 6.1 on 2026-10-07 12:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_apithrottlestate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccessToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_prefix', models.CharField(max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_tokens', to='common.apiaccesstoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API 访问令牌',
                'verbose_name_plural': 'API 访问令牌',
                'ordering': ['-created_at'],
            },
        ),
    ]
