# Generated by Django 6.1 on 2026-10-07 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_migrate_legacy_api_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=48)),
                ('subject_hash', models.CharField(blank=True, default='', max_length=64)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': '安全审计事件',
                'verbose_name_plural': '安全审计事件',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='common_secu_event_t_174bc4_idx')],
            },
        ),
    ]
