# Generated by Django 6.1 on 2026-08-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
    ]
