from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .auth_views import RateLimitedLoginView
from apps.workflow import web_views as workflow_web_views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', RateLimitedLoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('password/change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change_form.html',
        success_url='/password/change/done/',
    ), name='password_change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html',
    ), name='password_change_done'),
    path('assets/lookup/', views.asset_lookup, name='asset_lookup'),
    path('warehouse/', views.warehouse_management, name='warehouse_management'),
    path('warehouse/items/new/', views.warehouse_item_create, name='warehouse_item_create'),
    path('warehouse/low-stock/', views.low_stock_alerts, name='low_stock_alerts'),
    path('warehouse/replenishment/', views.replenishment_suggestions, name='replenishment_suggestions'),
    path('warehouse/purchase-drafts/', views.purchase_draft_list, name='purchase_draft_list'),
    path('warehouse/purchase-drafts/<uuid:purchase_id>/', views.purchase_draft_detail, name='purchase_draft_detail'),
    path('warehouse/purchase-drafts/<uuid:purchase_id>/edit/', views.purchase_draft_edit, name='purchase_draft_edit'),
    path('warehouse/purchase-drafts/<uuid:purchase_id>/delete/', views.purchase_draft_delete, name='purchase_draft_delete'),
    path('warehouse/purchase-orders/', views.purchase_order_list, name='purchase_order_list'),
    path('warehouse/purchase-orders/<uuid:order_id>/', views.purchase_order_detail, name='purchase_order_detail'),
    path('warehouse/purchase-orders/<uuid:order_id>/profile-template/', views.purchase_order_profile_template, name='purchase_order_profile_template'),
    path('reports/supplier-prices/', views.supplier_price_history, name='supplier_price_history'),
    path('reports/supplier-prices.csv', views.supplier_price_history_export, name='supplier_price_history_export'),
    path('reports/supplier-reconciliation/', views.supplier_reconciliation, name='supplier_reconciliation'),
    path('reports/supplier-reconciliation.csv', views.supplier_reconciliation_export, name='supplier_reconciliation_export'),
    path('warehouse/conversions/', views.inventory_conversion, name='inventory_conversion'),
    path('warehouse/composite-units/', views.composite_unit_management, name='composite_unit_management'),
    path('warehouse/import/', views.inventory_import, name='inventory_import'),
    path('warehouse/assets/new/', views.warehouse_asset_edit, name='warehouse_asset_create'),
    path('warehouse/assets/<uuid:asset_id>/lifecycle/', views.asset_lifecycle, name='asset_lifecycle'),
    path('warehouse/assets/<uuid:asset_id>/', views.warehouse_asset_edit, name='warehouse_asset_edit'),
    path('warehouse/attachments/<uuid:attachment_id>/download/', views.asset_attachment_download, name='asset_attachment_download'),
    path('warehouse/stock-items/new/', views.warehouse_stock_item_edit, name='warehouse_stock_item_create'),
    path('warehouse/stock-items/<uuid:stock_item_id>/', views.warehouse_stock_item_edit, name='warehouse_stock_item_edit'),
    path('warehouse/setup/<str:section>/', views.warehouse_setup, name='warehouse_setup'),
    path('warehouse/setup/<str:section>/new/', views.warehouse_setup_edit, name='warehouse_setup_create'),
    path('warehouse/setup/<str:section>/<uuid:object_id>/', views.warehouse_setup_edit, name='warehouse_setup_edit'),
    path('warehouse/qr-labels/', views.warehouse_qr_labels, name='warehouse_qr_labels'),
    path('warehouse/quick-process/', views.quick_inventory_process, name='quick_inventory_process'),
    path('offline/operations/', workflow_web_views.offline_operation_list, name='offline_operation_list'),
    path('offline/operations/sync/', workflow_web_views.offline_operation_sync, name='offline_operation_sync'),
    path('inventory-checks/', views.inventory_check_list, name='inventory_check_list'),
    path('inventory-checks/new/', views.inventory_check_create, name='inventory_check_create'),
    path('inventory-checks/<uuid:task_id>/', views.inventory_check_detail, name='inventory_check_detail'),
    path('inventory-checks/<uuid:task_id>/export/', views.inventory_check_export, name='inventory_check_export'),
    path('requests/', views.request_list, name='request_list'),
    path('requests/new/', views.request_create, name='request_create'),
    path('requests/<uuid:request_id>/edit/', views.request_create, name='request_edit'),
    path('requests/templates/<uuid:template_id>/delete/', views.request_template_delete, name='request_template_delete'),
    path('requests/candidates/scan/', views.request_candidate_scan, name='request_candidate_scan'),
    path('my-loans/', views.my_loans, name='my_loans'),
    path('my-loans/<uuid:request_id>/extend/', workflow_web_views.loan_extension_create, name='loan_extension_create'),
    path('reservations/', workflow_web_views.reservation_dashboard, name='reservation_dashboard'),
    path('transactions/', views.transaction_list, name='transaction_list'),
    path('approvals/', workflow_web_views.approval_queue, name='approval_queue'),
    path('workflow/<uuid:request_id>/', workflow_web_views.workflow_detail, name='workflow_detail'),
    path('reports/', views.report_dashboard, name='report_dashboard'),
    path('reports/transactions.csv', views.transaction_export, name='transaction_export'),
    path('reports/stale-inventory/', views.stale_inventory_report, name='stale_inventory_report'),
    path('reports/stale-inventory.csv', views.stale_inventory_export, name='stale_inventory_export'),
    path('notifications/', views.notification_center, name='notification_center'),
    path('notifications/<uuid:notification_id>/open/', views.notification_open, name='notification_open'),
    path('permissions/', views.permission_management, name='permission_management'),
    path('system/audit/', views.audit_log_list, name='audit_log_list'),
    path('system/consistency/', views.consistency_check, name='consistency_check'),
    path('system/consistency.csv', views.consistency_check_export, name='consistency_check_export'),
    path('health/', views.health, name='health'),
    path('sw.js', views.service_worker, name='service_worker'),
    path('preferences/list/', views.list_preference_save, name='list_preference_save'),
]
