# Generated by Django 6.1 on 2026-08-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvallog',
            options={'verbose_name': '审批日志', 'verbose_name_plural': '审批日志'},
        ),
        migrations.AlterModelOptions(
            name='approvaltask',
            options={'verbose_name': '审批任务', 'verbose_name_plural': '审批任务'},
        ),
        migrations.AlterModelOptions(
            name='workflowrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '仓库申请', 'verbose_name_plural': '仓库申请'},
        ),
        migrations.AlterModelOptions(
            name='workflowrequestline',
            options={'verbose_name': '申请明细', 'verbose_name_plural': '申请明细'},
        ),
    ]
