# Generated by Django 6.1 on 2026-08-25 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_approvallog_options_alter_approvaltask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '出入库申请单', 'verbose_name_plural': '出入库申请单'},
        ),
        migrations.AlterModelOptions(
            name='workflowrequestline',
            options={'verbose_name': '申请物品明细', 'verbose_name_plural': '申请物品明细'},
        ),
    ]
