# Generated by Django 6.1 on 2026-08-25 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_asset_external_holder_company_and_more'),
        ('workflow', '0003_alter_workflowrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrequest',
            name='recipient_company',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='recipient_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='target_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_requests', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='target_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_requests', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='workflowrequest',
            name='request_type',
            field=models.CharField(choices=[('borrow', '借用'), ('return', '归还'), ('issue', '领用'), ('transfer', '调拨'), ('repair', '维修'), ('damage', '报损'), ('sale', '出售'), ('return_to_vendor', '退货给供应商'), ('scrap', '报废')], max_length=32),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('borrow', '借用'), ('return', '归还'), ('issue', '领用'), ('transfer', '调拨'), ('repair', '维修'), ('damage', '报损'), ('sale', '出售'), ('return_to_vendor', '退货给供应商'), ('scrap', '报废')], max_length=32)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('asset_status_before', models.CharField(blank=True, default='', max_length=32)),
                ('asset_status_after', models.CharField(blank=True, default='', max_length=32)),
                ('stock_quantity_before', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_quantity_after', models.PositiveIntegerField(blank=True, null=True)),
                ('holder_name', models.CharField(blank=True, default='', max_length=120)),
                ('holder_company', models.CharField(blank=True, default='', max_length=120)),
                ('holder_phone', models.CharField(blank=True, default='', max_length=32)),
                ('comment', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.asset')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='workflow.workflowrequest')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='inventory.warehouse')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.stockitem')),
                ('target_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': '库存动作台账',
                'verbose_name_plural': '库存动作台账',
                'ordering': ['-created_at'],
            },
        ),
    ]
