# Generated by Django 6.1 on 2026-08-25 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_workflowrequest_recipient_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaltask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approval_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='designated_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designated_workflow_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
