# Generated by Django 6.1 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_approvaltask_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvallog',
            options={'verbose_name': '流程操作日志', 'verbose_name_plural': '流程操作日志'},
        ),
        migrations.AlterModelOptions(
            name='approvaltask',
            options={'verbose_name': '审批任务审计记录', 'verbose_name_plural': '审批任务审计记录'},
        ),
        migrations.AlterModelOptions(
            name='workflowrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '申请单审计记录', 'verbose_name_plural': '申请单审计记录'},
        ),
        migrations.AlterModelOptions(
            name='workflowrequestline',
            options={'verbose_name': '申请物品行（随申请单）', 'verbose_name_plural': '申请物品行（随申请单）'},
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='usage_location',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
