# Generated by Django 6.1 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_approvallog_options_alter_approvaltask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrequest',
            name='is_hidden_by_applicant',
            field=models.BooleanField(default=False),
        ),
    ]
