# Generated by Django 6.1 on 2026-08-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_workflowrequest_is_hidden_by_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='project_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='work_order_no',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='contact_source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='is_quick_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='project_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='work_order_no',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
