# Generated by Django 6.1 on 2026-08-27 02:40

import django.utils.timezone
from django.db import migrations, models


def backfill_business_dates_and_inventory_numbers(apps, schema_editor):
    WorkflowRequest = apps.get_model('workflow', 'WorkflowRequest')
    InventoryTransaction = apps.get_model('workflow', 'InventoryTransaction')
    DailySequence = apps.get_model('common', 'DailySequence')

    for request in WorkflowRequest.objects.all().iterator():
        request.application_date = django.utils.timezone.localtime(request.created_at).date()
        request.transaction_date = request.application_date
        request.save(update_fields=['application_date', 'transaction_date'])

    for transaction in InventoryTransaction.objects.all().iterator():
        transaction.business_date = django.utils.timezone.localtime(transaction.created_at).date()
        transaction.save(update_fields=['business_date'])

    for request in WorkflowRequest.objects.filter(
        inventory_no__isnull=True,
        inventory_transactions__isnull=False,
    ).distinct().order_by('created_at', 'id').iterator():
        sequence_date = request.transaction_date
        sequence, _ = DailySequence.objects.get_or_create(
            prefix='IO',
            sequence_date=sequence_date,
            defaults={'last_number': 0},
        )
        sequence.last_number += 1
        sequence.save(update_fields=['last_number', 'updated_at'])
        request.inventory_no = f'IO-{sequence_date:%Y%m%d}-{sequence.last_number:06d}'
        request.save(update_fields=['inventory_no'])


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_dailysequence'),
        ('workflow', '0008_inventorytransaction_cost_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='business_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='application_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='inventory_no',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='workflowrequest',
            name='expected_return_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.RunPython(backfill_business_dates_and_inventory_numbers, migrations.RunPython.noop),
    ]
