# Generated by Django 6.1 on 2026-08-27 02:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_department_options_alter_userprofile_options'),
        ('inventory', '0012_inventorychecktask_reopen_note_and_more'),
        ('workflow', '0009_inventorytransaction_business_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['business_date'], name='workflow_in_busines_b91837_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['action', 'business_date'], name='workflow_in_action_5c77df_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrequest',
            index=models.Index(fields=['application_date'], name='workflow_wo_applica_ab1a86_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrequest',
            index=models.Index(fields=['transaction_date'], name='workflow_wo_transac_1621b3_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrequest',
            index=models.Index(fields=['status', 'application_date'], name='workflow_wo_status_cc4eda_idx'),
        ),
    ]
