# Generated by Django 6.1 on 2026-08-28 02:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_reservations_and_loans(apps, schema_editor):
    WorkflowRequestLine = apps.get_model('workflow', 'WorkflowRequestLine')
    InventoryReservation = apps.get_model('workflow', 'InventoryReservation')
    StockItemLoan = apps.get_model('workflow', 'StockItemLoan')
    StockItemHolding = apps.get_model('inventory', 'StockItemHolding')

    active_statuses = {'pending', 'approved', 'waiting_warehouse'}
    outbound_types = {'borrow', 'issue', 'sale'}
    reserved_asset_ids = set()
    lines = WorkflowRequestLine.objects.filter(
        request__status__in=active_statuses,
        request__request_type__in=outbound_types,
    ).select_related('request').order_by('request__created_at', 'created_at')
    for line in lines.iterator():
        if line.asset_id:
            if line.asset_id in reserved_asset_ids:
                continue
            reserved_asset_ids.add(line.asset_id)
        InventoryReservation.objects.create(
            request_line_id=line.id,
            asset_id=line.asset_id,
            stock_item_id=line.stock_item_id,
            quantity=line.quantity,
            status='active',
        )

    for holding in StockItemHolding.objects.filter(quantity__gt=0).iterator():
        remaining = holding.quantity
        borrow_lines = WorkflowRequestLine.objects.filter(
            request__applicant_id=holding.holder_id,
            request__request_type='borrow',
            request__status='done',
            request__is_quick_process=False,
            stock_item_id=holding.stock_item_id,
            request__expected_return_date__isnull=False,
        ).select_related('request').order_by('-request__transaction_date', '-created_at')
        for line in borrow_lines.iterator():
            if remaining <= 0:
                break
            outstanding = min(line.quantity, remaining)
            StockItemLoan.objects.create(
                borrower_id=holding.holder_id,
                stock_item_id=holding.stock_item_id,
                source_line_id=line.id,
                original_quantity=line.quantity,
                outstanding_quantity=outstanding,
                expected_return_date=line.request.expected_return_date,
                status='active',
            )
            remaining -= outstanding


def no_op_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_stockitemholding'),
        ('workflow', '0010_inventorytransaction_workflow_in_busines_b91837_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnReminderLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_key', models.CharField(max_length=180, unique=True)),
                ('reminder_date', models.DateField(default=django.utils.timezone.localdate)),
                ('stage', models.CharField(max_length=16)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_reminder_logs', to=settings.AUTH_USER_MODEL)),
                ('request_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_reminder_logs', to='workflow.workflowrequestline')),
            ],
            options={
                'verbose_name': '归还提醒发送记录',
                'verbose_name_plural': '归还提醒发送记录',
                'ordering': ['-reminder_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItemLoan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_quantity', models.PositiveIntegerField()),
                ('outstanding_quantity', models.PositiveIntegerField()),
                ('expected_return_date', models.DateField()),
                ('status', models.CharField(choices=[('active', '借用中'), ('returned', '已归还')], default='active', max_length=16)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_item_loans', to=settings.AUTH_USER_MODEL)),
                ('source_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_loan', to='workflow.workflowrequestline')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': '耗材借用明细',
                'verbose_name_plural': '耗材借用明细',
                'ordering': ['expected_return_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', '预占中'), ('released', '已释放'), ('consumed', '已执行')], default='active', max_length=16)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.asset')),
                ('request_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='workflow.workflowrequestline')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': '库存预占记录',
                'verbose_name_plural': '库存预占记录',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('asset__isnull', False), ('stock_item__isnull', True)), models.Q(('asset__isnull', True), ('stock_item__isnull', False)), _connector='OR'), name='reservation_exactly_one_inventory_target'), models.UniqueConstraint(condition=models.Q(('asset__isnull', False), ('status', 'active')), fields=('asset',), name='unique_active_asset_reservation')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRequestTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('request_type', models.CharField(choices=[('borrow', '借用'), ('return', '归还'), ('issue', '领用'), ('transfer', '调拨'), ('repair', '维修'), ('damage', '报损'), ('sale', '出售'), ('return_to_vendor', '退货给供应商'), ('scrap', '报废')], max_length=32)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=120)),
                ('recipient_company', models.CharField(blank=True, default='', max_length=120)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=32)),
                ('usage_location', models.CharField(blank=True, default='', max_length=160)),
                ('project_code', models.CharField(blank=True, default='', max_length=80)),
                ('work_order_no', models.CharField(blank=True, default='', max_length=80)),
                ('reason', models.TextField(blank=True, default='')),
                ('default_borrow_days', models.PositiveSmallIntegerField(default=7)),
                ('designated_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designated_request_templates', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_request_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '常用申请模板',
                'verbose_name_plural': '常用申请模板',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_workflow_template_owner_name')],
            },
        ),
        migrations.RunPython(backfill_reservations_and_loans, no_op_reverse),
    ]
