# Generated by Django 6.1 on 2026-08-28 03:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from datetime import timedelta


def initialize_pending_reservation_expiry(apps, schema_editor):
    InventoryReservation = apps.get_model('workflow', 'InventoryReservation')
    InventoryReservation.objects.filter(
        status='active',
        request_line__request__status='pending',
    ).update(expires_at=timezone.now() + timedelta(hours=72))


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_returnreminderlog_stockitemloan_inventoryreservation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreservation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='release_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_inventory_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(initialize_pending_reservation_expiry, migrations.RunPython.noop),
        migrations.CreateModel(
            name='LoanExtensionRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_return_date', models.DateField()),
                ('requested_return_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回'), ('canceled', '已撤回')], default='pending', max_length=16)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_extension_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loan_extension_requests', to=settings.AUTH_USER_MODEL)),
                ('source_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_extension_requests', to='workflow.workflowrequest')),
            ],
            options={
                'verbose_name': '借用延期申请',
                'verbose_name_plural': '借用延期申请',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('source_request',), name='unique_pending_extension_per_source_request')],
            },
        ),
    ]
