# Generated by Django 6.1 on 2026-09-07 08:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_customer_serviceprovider_supplier_project_and_more'),
        ('workflow', '0012_inventoryreservation_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrequest',
            name='customer_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_requests', to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='project_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_requests', to='inventory.project'),
        ),
        migrations.AddField(
            model_name='workflowrequest',
            name='work_order_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_requests', to='inventory.workorder'),
        ),
        migrations.AddField(
            model_name='workflowrequesttemplate',
            name='customer_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_request_templates', to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='workflowrequesttemplate',
            name='project_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_request_templates', to='inventory.project'),
        ),
        migrations.AddField(
            model_name='workflowrequesttemplate',
            name='work_order_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_request_templates', to='inventory.workorder'),
        ),
        migrations.CreateModel(
            name='OfflineOperation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_operation_id', models.UUIDField(unique=True, verbose_name='客户端操作编号')),
                ('operation_type', models.CharField(choices=[('quick_inventory', '离线快速出入库')], default='quick_inventory', max_length=32, verbose_name='操作类型')),
                ('status', models.CharField(choices=[('pending', '待复核'), ('applied', '已执行'), ('conflict', '存在冲突'), ('rejected', '已拒绝')], default='pending', max_length=16, verbose_name='状态')),
                ('payload', models.JSONField(default=dict, verbose_name='离线数据')),
                ('conflict_details', models.JSONField(blank=True, default=dict, verbose_name='冲突详情')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误说明')),
                ('client_created_at', models.DateTimeField(verbose_name='客户端登记时间')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='服务器接收时间')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='复核时间')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='同步/执行次数')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_operations', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('resulting_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offline_operation', to='workflow.workflowrequest', verbose_name='生成的出入库单')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_offline_operations', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '离线操作',
                'verbose_name_plural': '离线操作',
                'ordering': ['-client_created_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'received_at'], name='workflow_of_status_bc4657_idx'), models.Index(fields=['operator', 'client_created_at'], name='workflow_of_operato_77645e_idx')],
            },
        ),
    ]
