# Generated by Django 5.2.17 on 2026-09-24 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_asset_status_and_more'),
        ('workflow', '0013_workflowrequest_customer_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrequest',
            name='composite_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_requests', to='inventory.compositeunit', verbose_name='成品设备'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='action',
            field=models.CharField(choices=[('borrow', '借用'), ('return', '归还'), ('issue', '领用'), ('transfer', '调拨'), ('repair', '维修'), ('damage', '报损'), ('sale', '出售'), ('return_to_vendor', '退货给供应商'), ('scrap', '报废'), ('assemble', '成品组装'), ('disassemble', '成品拆散')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowrequest',
            name='request_type',
            field=models.CharField(choices=[('borrow', '借用'), ('return', '归还'), ('issue', '领用'), ('transfer', '调拨'), ('repair', '维修'), ('damage', '报损'), ('sale', '出售'), ('return_to_vendor', '退货给供应商'), ('scrap', '报废'), ('assemble', '成品组装'), ('disassemble', '成品拆散')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowrequesttemplate',
            name='request_type',
            field=models.CharField(choices=[('borrow', '借用'), ('return', '归还'), ('issue', '领用'), ('transfer', '调拨'), ('repair', '维修'), ('damage', '报损'), ('sale', '出售'), ('return_to_vendor', '退货给供应商'), ('scrap', '报废'), ('assemble', '成品组装'), ('disassemble', '成品拆散')], max_length=32),
        ),
    ]
