# Generated by Django 5.2.17 on 2026-09-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_workflowrequest_composite_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='action',
            field=models.CharField(choices=[('borrow', '借用'), ('return', '归还'), ('issue', '领用'), ('transfer', '调拨'), ('repair', '维修'), ('damage', '报损'), ('sale', '出售'), ('return_to_vendor', '退货给供应商'), ('scrap', '报废')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowrequest',
            name='request_type',
            field=models.CharField(choices=[('borrow', '借用'), ('return', '归还'), ('issue', '领用'), ('transfer', '调拨'), ('repair', '维修'), ('damage', '报损'), ('sale', '出售'), ('return_to_vendor', '退货给供应商'), ('scrap', '报废')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowrequesttemplate',
            name='request_type',
            field=models.CharField(choices=[('borrow', '借用'), ('return', '归还'), ('issue', '领用'), ('transfer', '调拨'), ('repair', '维修'), ('damage', '报损'), ('sale', '出售'), ('return_to_vendor', '退货给供应商'), ('scrap', '报废')], max_length=32),
        ),
    ]
