# Generated by Django 6.1 on 2026-09-29 14:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_asset_system_asset_no'),
        ('workflow', '0015_alter_inventorytransaction_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_no', models.CharField(default='', max_length=80, unique=True, verbose_name='采购草稿编号')),
                ('application_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='申请日期')),
                ('status', models.CharField(choices=[('draft', '采购草稿'), ('archived', '已归档')], default='draft', max_length=16, verbose_name='状态')),
                ('reason', models.TextField(blank=True, default='', verbose_name='采购原因')),
                ('note', models.TextField(blank=True, default='', verbose_name='补充说明')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_drafts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '采购申请草稿',
                'verbose_name_plural': '采购申请草稿',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(max_length=120, verbose_name='物品名称')),
                ('code_snapshot', models.CharField(blank=True, default='', max_length=80, verbose_name='物品编码')),
                ('management_mode', models.CharField(default='', max_length=32, verbose_name='管理方式')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='计划采购数量')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('reference_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='参考单价（元）')),
                ('reference_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='参考金额（元）')),
                ('supplier_snapshot', models.CharField(blank=True, default='', max_length=120, verbose_name='供应商快照')),
                ('warehouse_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='仓库快照')),
                ('location_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='库位快照')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='明细备注')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_lines', to='inventory.itemtype', verbose_name='资产物品类型来源')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='workflow.purchaserequest', verbose_name='采购草稿')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_lines', to='inventory.stockitem', verbose_name='耗材配件来源')),
            ],
            options={
                'verbose_name': '采购申请明细',
                'verbose_name_plural': '采购申请明细',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['application_date'], name='workflow_pu_applica_eff739_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequest',
            index=models.Index(fields=['status', 'application_date'], name='workflow_pu_status_8d5b36_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(('item_type__isnull', False), ('stock_item__isnull', False), _connector='OR'), name='purchase_line_has_source'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestline',
            constraint=models.CheckConstraint(condition=models.Q(('item_type__isnull', False), ('stock_item__isnull', False), _negated=True), name='purchase_line_one_source'),
        ),
    ]
