# Generated by Django 5.2.17 on 2026-09-29 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_purchaserequest_purchaserequestline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='approval_comment',
            field=models.TextField(blank=True, default='', verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批处理时间'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='designated_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designated_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='指定审批人'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交审批时间'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', '采购草稿'), ('pending_approval', '待采购审批'), ('approved', '采购已通过'), ('rejected', '采购已驳回'), ('archived', '已归档')], default='draft', max_length=16, verbose_name='状态'),
        ),
    ]
