# Generated by Django 5.2.17 on 2026-09-29 15:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_asset_system_asset_no'),
        ('workflow', '0017_purchaserequest_approval_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='action',
            field=models.CharField(choices=[('borrow', '借用'), ('return', '归还'), ('issue', '领用'), ('transfer', '调拨'), ('repair', '维修'), ('damage', '报损'), ('sale', '出售'), ('return_to_vendor', '退货给供应商'), ('scrap', '报废'), ('purchase_receipt', '采购入库')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowrequest',
            name='request_type',
            field=models.CharField(choices=[('borrow', '借用'), ('return', '归还'), ('issue', '领用'), ('transfer', '调拨'), ('repair', '维修'), ('damage', '报损'), ('sale', '出售'), ('return_to_vendor', '退货给供应商'), ('scrap', '报废'), ('purchase_receipt', '采购入库')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workflowrequesttemplate',
            name='request_type',
            field=models.CharField(choices=[('borrow', '借用'), ('return', '归还'), ('issue', '领用'), ('transfer', '调拨'), ('repair', '维修'), ('damage', '报损'), ('sale', '出售'), ('return_to_vendor', '退货给供应商'), ('scrap', '报废'), ('purchase_receipt', '采购入库')], max_length=32),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(default='', max_length=80, unique=True, verbose_name='采购订单编号')),
                ('order_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='下单日期')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='预计到货日期')),
                ('status', models.CharField(choices=[('draft', '待下达'), ('ordered', '已下达'), ('partial_received', '部分到货'), ('received', '已全部到货'), ('canceled', '已取消')], default='draft', max_length=24, verbose_name='状态')),
                ('note', models.TextField(blank=True, default='', verbose_name='订单说明')),
                ('ordered_at', models.DateTimeField(blank=True, null=True, verbose_name='下达时间')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='workflow.purchaserequest', verbose_name='采购申请')),
            ],
            options={
                'verbose_name': '采购订单',
                'verbose_name_plural': '采购订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(max_length=120, verbose_name='物品名称')),
                ('code_snapshot', models.CharField(blank=True, default='', max_length=80, verbose_name='物品编码')),
                ('management_mode', models.CharField(default='', max_length=32, verbose_name='管理方式')),
                ('ordered_quantity', models.PositiveIntegerField(default=1, verbose_name='订购数量')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='已到货数量')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='采购单价（元）')),
                ('supplier_snapshot', models.CharField(blank=True, default='', max_length=120, verbose_name='供应商快照')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='明细备注')),
                ('item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_lines', to='inventory.itemtype', verbose_name='资产物品类型来源')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='workflow.purchaseorder', verbose_name='采购订单')),
                ('purchase_request_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_line', to='workflow.purchaserequestline', verbose_name='采购申请明细')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_lines', to='inventory.stockitem', verbose_name='耗材配件来源')),
            ],
            options={
                'verbose_name': '采购订单明细',
                'verbose_name_plural': '采购订单明细',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_no', models.CharField(default='', max_length=80, unique=True, verbose_name='到货登记编号')),
                ('received_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='到货日期')),
                ('note', models.TextField(blank=True, default='', verbose_name='到货说明')),
                ('inventory_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt', to='workflow.workflowrequest', verbose_name='采购入库单')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='workflow.purchaseorder', verbose_name='采购订单')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': '采购到货登记',
                'verbose_name_plural': '采购到货登记',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_quantity', models.PositiveIntegerField(default=1, verbose_name='本次到货数量')),
                ('created_asset_ids', models.JSONField(blank=True, default=list, verbose_name='本次生成资产编号')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='明细备注')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='入库库位')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='入库仓库')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='workflow.purchaseorderline', verbose_name='采购订单明细')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='workflow.purchasereceipt', verbose_name='到货登记')),
            ],
            options={
                'verbose_name': '采购到货明细',
                'verbose_name_plural': '采购到货明细',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='workflow_pu_order_d_fd6d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'order_date'], name='workflow_pu_status_124a0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__lte', models.F('ordered_quantity'))), name='purchase_order_received_lte_ordered'),
        ),
    ]
